/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/utils/app-footer.vue')['default']
    ButtonMenu: typeof import('./components/utils/button-menu.vue')['default']
    DeleteModal: typeof import('./components/utils/delete-modal.vue')['default']
    InputPassword: typeof import('./components/login/input-password.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SignIn: typeof import('./components/login/sign-in.vue')['default']
    SignUp: typeof import('./components/login/sign-up.vue')['default']
  }
}
